# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rendezvous.protos import rendezvous_pb2 as rendezvous_dot_protos_dot_rendezvous__pb2


class RendezvousServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.registerRequest = channel.unary_unary(
                '/rendezvous.RendezvousService/registerRequest',
                request_serializer=rendezvous_dot_protos_dot_rendezvous__pb2.RegisterRequestMessage.SerializeToString,
                response_deserializer=rendezvous_dot_protos_dot_rendezvous__pb2.RegisterRequestResponse.FromString,
                )
        self.registerBranch = channel.unary_unary(
                '/rendezvous.RendezvousService/registerBranch',
                request_serializer=rendezvous_dot_protos_dot_rendezvous__pb2.RegisterBranchMessage.SerializeToString,
                response_deserializer=rendezvous_dot_protos_dot_rendezvous__pb2.RegisterBranchResponse.FromString,
                )
        self.registerBranches = channel.unary_unary(
                '/rendezvous.RendezvousService/registerBranches',
                request_serializer=rendezvous_dot_protos_dot_rendezvous__pb2.RegisterBranchesMessage.SerializeToString,
                response_deserializer=rendezvous_dot_protos_dot_rendezvous__pb2.RegisterBranchesResponse.FromString,
                )
        self.closeBranch = channel.unary_unary(
                '/rendezvous.RendezvousService/closeBranch',
                request_serializer=rendezvous_dot_protos_dot_rendezvous__pb2.CloseBranchMessage.SerializeToString,
                response_deserializer=rendezvous_dot_protos_dot_rendezvous__pb2.Empty.FromString,
                )
        self.waitRequest = channel.unary_unary(
                '/rendezvous.RendezvousService/waitRequest',
                request_serializer=rendezvous_dot_protos_dot_rendezvous__pb2.WaitRequestMessage.SerializeToString,
                response_deserializer=rendezvous_dot_protos_dot_rendezvous__pb2.WaitRequestResponse.FromString,
                )
        self.checkRequest = channel.unary_unary(
                '/rendezvous.RendezvousService/checkRequest',
                request_serializer=rendezvous_dot_protos_dot_rendezvous__pb2.CheckRequestMessage.SerializeToString,
                response_deserializer=rendezvous_dot_protos_dot_rendezvous__pb2.CheckRequestResponse.FromString,
                )
        self.checkRequestByRegions = channel.unary_unary(
                '/rendezvous.RendezvousService/checkRequestByRegions',
                request_serializer=rendezvous_dot_protos_dot_rendezvous__pb2.CheckRequestByRegionsMessage.SerializeToString,
                response_deserializer=rendezvous_dot_protos_dot_rendezvous__pb2.CheckRequestByRegionsResponse.FromString,
                )
        self.getPreventedInconsistencies = channel.unary_unary(
                '/rendezvous.RendezvousService/getPreventedInconsistencies',
                request_serializer=rendezvous_dot_protos_dot_rendezvous__pb2.Empty.SerializeToString,
                response_deserializer=rendezvous_dot_protos_dot_rendezvous__pb2.GetPreventedInconsistenciesResponse.FromString,
                )


class RendezvousServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def registerRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def registerBranch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def registerBranches(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def closeBranch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def waitRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def checkRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def checkRequestByRegions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getPreventedInconsistencies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RendezvousServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'registerRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.registerRequest,
                    request_deserializer=rendezvous_dot_protos_dot_rendezvous__pb2.RegisterRequestMessage.FromString,
                    response_serializer=rendezvous_dot_protos_dot_rendezvous__pb2.RegisterRequestResponse.SerializeToString,
            ),
            'registerBranch': grpc.unary_unary_rpc_method_handler(
                    servicer.registerBranch,
                    request_deserializer=rendezvous_dot_protos_dot_rendezvous__pb2.RegisterBranchMessage.FromString,
                    response_serializer=rendezvous_dot_protos_dot_rendezvous__pb2.RegisterBranchResponse.SerializeToString,
            ),
            'registerBranches': grpc.unary_unary_rpc_method_handler(
                    servicer.registerBranches,
                    request_deserializer=rendezvous_dot_protos_dot_rendezvous__pb2.RegisterBranchesMessage.FromString,
                    response_serializer=rendezvous_dot_protos_dot_rendezvous__pb2.RegisterBranchesResponse.SerializeToString,
            ),
            'closeBranch': grpc.unary_unary_rpc_method_handler(
                    servicer.closeBranch,
                    request_deserializer=rendezvous_dot_protos_dot_rendezvous__pb2.CloseBranchMessage.FromString,
                    response_serializer=rendezvous_dot_protos_dot_rendezvous__pb2.Empty.SerializeToString,
            ),
            'waitRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.waitRequest,
                    request_deserializer=rendezvous_dot_protos_dot_rendezvous__pb2.WaitRequestMessage.FromString,
                    response_serializer=rendezvous_dot_protos_dot_rendezvous__pb2.WaitRequestResponse.SerializeToString,
            ),
            'checkRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.checkRequest,
                    request_deserializer=rendezvous_dot_protos_dot_rendezvous__pb2.CheckRequestMessage.FromString,
                    response_serializer=rendezvous_dot_protos_dot_rendezvous__pb2.CheckRequestResponse.SerializeToString,
            ),
            'checkRequestByRegions': grpc.unary_unary_rpc_method_handler(
                    servicer.checkRequestByRegions,
                    request_deserializer=rendezvous_dot_protos_dot_rendezvous__pb2.CheckRequestByRegionsMessage.FromString,
                    response_serializer=rendezvous_dot_protos_dot_rendezvous__pb2.CheckRequestByRegionsResponse.SerializeToString,
            ),
            'getPreventedInconsistencies': grpc.unary_unary_rpc_method_handler(
                    servicer.getPreventedInconsistencies,
                    request_deserializer=rendezvous_dot_protos_dot_rendezvous__pb2.Empty.FromString,
                    response_serializer=rendezvous_dot_protos_dot_rendezvous__pb2.GetPreventedInconsistenciesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rendezvous.RendezvousService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RendezvousService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def registerRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rendezvous.RendezvousService/registerRequest',
            rendezvous_dot_protos_dot_rendezvous__pb2.RegisterRequestMessage.SerializeToString,
            rendezvous_dot_protos_dot_rendezvous__pb2.RegisterRequestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def registerBranch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rendezvous.RendezvousService/registerBranch',
            rendezvous_dot_protos_dot_rendezvous__pb2.RegisterBranchMessage.SerializeToString,
            rendezvous_dot_protos_dot_rendezvous__pb2.RegisterBranchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def registerBranches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rendezvous.RendezvousService/registerBranches',
            rendezvous_dot_protos_dot_rendezvous__pb2.RegisterBranchesMessage.SerializeToString,
            rendezvous_dot_protos_dot_rendezvous__pb2.RegisterBranchesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def closeBranch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rendezvous.RendezvousService/closeBranch',
            rendezvous_dot_protos_dot_rendezvous__pb2.CloseBranchMessage.SerializeToString,
            rendezvous_dot_protos_dot_rendezvous__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def waitRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rendezvous.RendezvousService/waitRequest',
            rendezvous_dot_protos_dot_rendezvous__pb2.WaitRequestMessage.SerializeToString,
            rendezvous_dot_protos_dot_rendezvous__pb2.WaitRequestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def checkRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rendezvous.RendezvousService/checkRequest',
            rendezvous_dot_protos_dot_rendezvous__pb2.CheckRequestMessage.SerializeToString,
            rendezvous_dot_protos_dot_rendezvous__pb2.CheckRequestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def checkRequestByRegions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rendezvous.RendezvousService/checkRequestByRegions',
            rendezvous_dot_protos_dot_rendezvous__pb2.CheckRequestByRegionsMessage.SerializeToString,
            rendezvous_dot_protos_dot_rendezvous__pb2.CheckRequestByRegionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getPreventedInconsistencies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rendezvous.RendezvousService/getPreventedInconsistencies',
            rendezvous_dot_protos_dot_rendezvous__pb2.Empty.SerializeToString,
            rendezvous_dot_protos_dot_rendezvous__pb2.GetPreventedInconsistenciesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
