# sudo docker run -it -p 8001:8001 mafaldacf/rendezvous
# sudo docker run -it -p 8002:8002 mafaldacf/endezvous

version: "3.9"
services:
  metadata-server-eu:
    image: mafaldacf/rendezvous:latest
    hostname: rendezvous-eu
    ports:
      - 8001:8001
    entrypoint: sh -c "cd metadata-server && ./start.sh run server eu"
  metadata-server-us:
    image: mafaldacf/rendezvous:latest
    hostname: rendezvous-us
    ports:
      - 8002:8002
    entrypoint: sh -c "cd metadata-server && ./start.sh run server us"

  database-monitor-cache-eu:
    image: mafaldacf/rendezvous:latest
    entrypoint: sh -c "cd database-monitor && python3 main.py -cp aws -d cache -r eu"
    volumes:
      - /home/ubuntu/.aws/config:/root/.aws/config
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials
  database-monitor-cache-us:
    image: mafaldacf/rendezvous:latest
    entrypoint: sh -c "cd database-monitor && python3 main.py -cp aws -d cache -r us"
    volumes:
      - /home/ubuntu/.aws/config:/root/.aws/config
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials
  database-monitor-dynamo-eu:
    image: mafaldacf/rendezvous:latest
    entrypoint: sh -c "cd database-monitor && python3 main.py -cp aws -d dynamo -r eu"
    volumes:
      - /home/ubuntu/.aws/config:/root/.aws/config
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials
  database-monitor-dynamo-us:
    image: mafaldacf/rendezvous:latest
    entrypoint: sh -c "cd database-monitor && python3 main.py -cp aws -d dynamo -r us"
    volumes:
      - /home/ubuntu/.aws/config:/root/.aws/config
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials
  database-monitor-mysql-eu:
    image: mafaldacf/rendezvous:latest
    entrypoint: sh -c "cd database-monitor && python3 main.py -cp aws -d mysql -r eu"
    volumes:
      - /home/ubuntu/.aws/config:/root/.aws/config
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials
  database-monitor-mysql-us:
    image: mafaldacf/rendezvous:latest
    entrypoint: sh -c "cd database-monitor && python3 main.py -cp aws -d mysql -r us"
    volumes:
      - /home/ubuntu/.aws/config:/root/.aws/config
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials
  database-monitor-s3-eu:
    image: mafaldacf/rendezvous:latest
    entrypoint: sh -c "cd database-monitor && python3 main.py -cp aws -d s3 -r eu"
    volumes:
      - /home/ubuntu/.aws/config:/root/.aws/config
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials
  database-monitor-s3-us:
    image: mafaldacf/rendezvous:latest
    entrypoint: sh -c "cd database-monitor && python3 main.py -cp aws -d s3 -r us"
    volumes:
      - /home/ubuntu/.aws/config:/root/.aws/config
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials
