# sudo docker run -it -p 8001:8001 --hostname rendezvous-eu-central-1 --network socialnetwork_default rendezvous
# sudo docker run -it -p 8002:8002 --hostname rendezvous-us-east-1 --network socialnetwork_default rendezvous

version: "3.9"
services:
  rendezvous-eu-central-1:
    image: rendezvous:latest
    hostname: rendezvous-eu-central-1
    ports:
      - 8001:8001
    networks:
      - socialnetwork_default
    entrypoint: ./start.sh run server eu-central-1
  rendezvous-us-east-1:
    image: rendezvous:latest
    hostname: rendezvous-us-east-1
    ports:
      - 8002:8002
    networks:
      - socialnetwork_default
    entrypoint: ./start.sh run server us-east-1

networks:
  socialnetwork_default:
    external:
      name: socialnetwork_default