FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV MY_INSTALL_DIR=$HOME/.local
ENV PATH="$MY_INSTALL_DIR/bin:$PATH"

ENV GRPC_VERSION=1.52.0
ENV CMAKE_VERSION=3.19.6
ENV JSON_VERSION=3.11.2
ENV BUILD_DEPS="autoconf git pkg-config cmake automake libtool curl zip unzip tar make wget g++ nano"

# Tools
RUN apt-get update \
  && apt-get install -y ${BUILD_DEPS} \
  && apt-get clean

# Create ./local directory for CMake, gRPC and Protobuf
RUN mkdir -p $MY_INSTALL_DIR

# Update CMake
RUN wget -q -O cmake-linux.sh https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.sh \
    && sh cmake-linux.sh -- --skip-license --prefix=$MY_INSTALL_DIR \
    && rm cmake-linux.sh

# Install gRPC and Protobuf dependencies
RUN git clone --recurse-submodules -b v${GRPC_VERSION} --depth 1 --shallow-submodules https://github.com/grpc/grpc \
    && cd grpc \
    && mkdir -p cmake/build \
    && cd cmake/build \
    && cmake -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DgRPC_BUILD_CSHARP_EXT=OFF -DCMAKE_INSTALL_PREFIX=$MY_INSTALL_DIR ../.. \
    && make -j 4 \
    && make install \
    && cd ../..

# Install JSON for C++
RUN git clone -b v${JSON_VERSION} --depth 1 https://github.com/nlohmann/json.git \
    && cd json \
    && mkdir build \
    && cd build \
    && cmake .. \
    && cmake --install .