duration: 300
threads: 200
words23: False 
params: [
    # [clients, metadata]
    #[1, 1],    [2, 1],    [3, 1],    [4, 1],    [5, 1],
    #[1, 10],   [2, 10],   [3, 10],   [4, 10],   [5, 10],
    [1, 50],  [2, 50],  [3, 50],  [4, 50],  #[5, 50]
]