duration: 150
threads: 200
words23: False 
params: [
    # [clients, metadata]
    [1, 1],    [2, 1],    [3, 1],    [4, 1],    [5, 1],
    [1, 10],   [2, 10],   [3, 10],   [4, 10],   [5, 10],
    [1, 100],  [2, 100],  [3, 100],  [4, 100],  #[5, 100]
]