# --------------------------------------------------------------------------------------------
# IMPORTANT REMINDER!!!
#
# Although the project contains a dockerfile to run the metadata server, the server
# runs in the native OS without any containerization for better evaluation performance
# 
# As a result, it is necessary to create an EC2 instance and manually transfer the source code
# Then, you connect to the EC2 instance and build the project with: ./manager.sh local build
# --------------------------------------------------------------------------------------------

# recommended to have a dedicated subfolder inside 'results'
results_dir: "results/thesis"
# make sure key has at least 500 permissions and we have the full path
ssh_key_path: "/home/mafaldacf/.ssh/rendezvous-eu.pem"

clients_ip: ["3.72.254.32", "3.70.217.238", "3.70.250.51", "3.72.11.231", "18.194.33.59"]
server_ip: "18.156.136.126"
server_port: 8001