metadata_validity_s: 30
close_branches_db_sleep_time_s: 35
close_branches_db: True
server_unavailable_sleep_time_s: 2

rendezvous: 
  address: localhost:8002

services:
  post_storage: 
    region: us
    datastores:
      aws_dynamo:
        region: us-east-1
        table: blobs