rendezvous: 
  address: localhost:8001

aws:
  mysql:
    host: antipode-lambda-eu.cluster-cowdztysvhul.eu-central-1.rds.amazonaws.com
    port: 3306
    user: antipode
    password: antipode
    db: antipode
    table: blobs
  dynamo:
    region: eu-central-1
    table: blobs
  s3:
    bucket: antipode-lambda-posts-eu-rendezvous
  cache:
    host: antipode-lambda-eu-001.gwkjt4.0001.euc1.cache.amazonaws.com
    port: 6379