rendezvous: 
  address: localhost:8001

aws:
  mysql:
    host: antipode-lambda-eu.cluster-cowdztysvhul.eu-central-1.rds.amazonaws.com
    port: 3306
    user: antipode
    password: antipode
    db: antipode
    client_table: blobs
    rendezvous_table: rendezvous
  dynamo:
    region: eu-central-1
    client_table: blobs
    rendezvous_table: rendezvous
  s3:
    bucket: antipode-lambda-posts-eu-rendezvous
    rendezvous_path: rendezvous
  cache:
    host: antipode-lambda-writer-001.gwkjt4.0001.euc1.cache.amazonaws.com
    port: 6379
    rendezvous_prefix: rendezvous
